meta_product_name: "Detours"
meta_title: "Detours - Explore your city the smart way"
meta_description: "Detour uses AI to create unique walking itineraries through hidden gems, cultural landmarks, and scenic routes so you enjoy your city like never before."
meta_image: "cover.png" # should exist in `app/assets/images/`
